server:
  port: 8080
  servlet:
    context-path: /da-application


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/dayoung_application"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "8uCH9LE9Xq9NPLz/ul3DRYxeQAv+wToJtPAAlSAxjvpIldJ5Ui3Qi1CocC2r19AX"

